name: temperaturer-etl

services:
  datainnsamler:
    build: ./datainnsamler
    volumes:
      - ./data:/data

  databehandler:
    build: ./databehandler
    volumes:
      - ./data:/data
    depends_on:
      - datainnsamler

# Smidig IT-2 © TIP AS, 2025